version: '3.7'

services:
  engine_service:
    container_name: challenge
    image: challenge:latest
    depends_on:
      - 'sql-server-db'
    build:
      context: './Challenge'
      dockerfile: ./Dockerfile
    ports:
      - '5000:7000'
    restart: always
